export type ContentPage = { slug: string; title: string; description: string; heading: string; sections: [string, string][]; faqs?: [string, string][]; article?: boolean }
export const faqs: [string, string][] = [
  ['What is an image QR code?', 'An image QR code blends a photo into the QR pattern while encoding a link or text. The photo is part of the design; scanning reads the encoded data, rather than downloading the original image.'],
  ['Can I make a QR code with a face or landscape?', 'Yes. Upload a portrait, landscape, or brand image, enter your link or text, and adjust strength, color mode, and detail. Choose a high-contrast photo and test the exported PNG.'],
  ['Is boring qrs free, and do I need an account?', 'The generator is free and works without login or signup. You can generate and download a PNG directly from the homepage.'],
  ['Are my uploaded images sent to a server?', 'QR generation and processing of uploaded photos happen in your browser. The optional random-photo button requests an image from an external provider.'],
  ['Will every artistic QR code scan?', 'Scanning depends on the photo, contrast, blend strength, size, lighting, and camera. Start around 50–70% strength, then test with multiple phones before sharing or printing.'],
  ['Do these QR codes expire?', 'The QR pattern directly encodes your data and has no service-controlled expiry. A linked website can still move, expire, or become unavailable. You cannot change the encoded destination after exporting the PNG.'],
]
export const pages: ContentPage[] = [
  { slug: 'qr-print-size-calculator', title: 'QR PNG Print Size Calculator — Pixels to cm | boring qrs', description: 'Convert your QR PNG width and print DPI into inches and centimeters. Plan the layout, keep the border, and test a printed proof.', heading: 'QR code PNG print size calculator', sections: [
    ['Find your export dimensions', 'Download the PNG and inspect its width in your image viewer or file properties. Enter the pixel width below along with your intended print resolution. The example is illustrative; use the dimensions of your own export.'],
    ['Understand the calculation', 'A 900-pixel-wide image printed at 300 dots per inch is 3 inches wide, or 7.62 centimeters. Changing the DPI changes the intended physical dimensions, not the encoded link. Resampling an image can blur edges, so preserve the original PNG when preparing a layout.'],
    ['A size calculation is not a scan guarantee', 'Artistic QR codes also depend on contrast, pattern density, viewing distance, lighting, and the camera. Keep the complete clear border, check the PNG at final size, and scan a printed proof before committing to a card or poster run.'],
  ] },
  { slug: 'qr-code-with-image', title: 'QR Code With an Image — Free Photo QR Generator | boring qrs', description: 'Blend your photo into a QR code for a link or text. Adjust color, strength and detail, then download a PNG for free without signing up.', heading: 'Create a QR code with your own image', sections: [
    ['A photo inside the QR pattern', 'boring qrs maps your image into the light and dark modules of a QR code. It keeps the recognizable corner markers and a clear border. This is different from a QR code that simply links to an uploaded photo: the photo becomes part of the visible design.'],
    ['Make your first image QR code', 'Open the generator, enter a short destination URL or text, and upload a photo. Start at 50–70% strength and compare grayscale with color. Adjust detail until the subject is recognizable, scan the preview, then download the PNG. Test the downloaded file too.'],
    ['Pick a photo that survives the pattern', 'A clear subject and distinct light and dark areas usually work better than a busy collage. Crop around the subject before uploading. If the pattern hides the subject, try another crop; if scanning fails, reduce the blend strength or use stronger contrast.'],
    ['What the scan opens', 'Scanning returns the link or text you entered. Your photo is not uploaded as a hosted file, and the exported code does not provide click analytics or editable destinations. Use a URL you control if you need to update the content behind the link.'],
  ], faqs: [faqs[0], faqs[3], faqs[5]] },
  { slug: 'portrait-qr-code', title: 'Portrait QR Code Generator — Turn a Face Into QR Art | boring qrs', description: 'Create a photo QR code with a portrait or face for a profile, portfolio, or business card. Free browser-based generator with PNG downloads.', heading: 'Turn a portrait into QR code art', sections: [
    ['Use a face people can recognize', 'Choose a well-lit portrait with a simple background. A face that fills much of the square crop is easier to recognize than a small face in a group photo. Use a photo you own or have permission to publish.'],
    ['Connect the portrait to your profile', 'Enter your public portfolio, social profile, or contact-page URL. Upload the portrait, compare grayscale and color, and adjust the strength while keeping enough contrast to scan. The code encodes that destination; it does not automatically create a contact card.'],
    ['Try it on a digital business card', 'Download your PNG and place it beside your name and a readable URL. Leave the QR border clear. Preview it at the actual display or print size and try more than one phone. Keep a plain QR alternative if your design cannot scan reliably.'],
  ], faqs: [faqs[1], faqs[4]] },
  { slug: 'landscape-qr-code', title: 'Landscape QR Code Generator — Scenic Photo QR Art | boring qrs', description: 'Blend scenery and nature photos into artistic QR codes for travel pages, photography portfolios, and event links. Free PNG export.', heading: 'Make a landscape photo QR code', sections: [
    ['Choose scenery with clear shapes', 'Mountains, a strong horizon, or a single tree can remain recognizable through a QR pattern. Very fine foliage or a uniformly pale sky can make the result harder to read. Crop a landscape into a square before uploading for more control over the composition.'],
    ['Link the scene to something useful', 'Encode a travel guide, gallery, event page, or location-page URL. The generator accepts the destination as text; it does not automatically add map coordinates, bookings, or tracking. Check that your chosen page opens without requiring an unexpected login.'],
    ['Create and check the final image', 'Upload your scenery or use the optional random-photo button. Start with moderate strength, compare color and grayscale, and scan the downloaded PNG. For a poster, test a sample at its intended size and viewing distance before producing a full print run.'],
  ], faqs: [faqs[3], faqs[4]] },
  { slug: 'qr-code-for-business-cards', title: 'Artistic QR Codes for Business Cards | boring qrs', description: 'Make a branded photo QR code for your portfolio or business website. Learn how to choose imagery, preserve the border, and test printed cards.', heading: 'A photo QR code for your business card', sections: [
    ['Give the scan a clear purpose', 'Link to a mobile-friendly portfolio, contact page, or business website. Add a short label such as View my portfolio so people know what to expect. Include a readable web address as a fallback.'],
    ['Blend a portrait or brand image', 'Upload an image with a clear focal point and enter the final URL. This tool blends an image across the QR pattern; it is not a dedicated center-logo editor. Test several strength settings and choose a design that works at the small size available on a card.'],
    ['Check the proof before ordering', 'Keep the light border around the QR code and avoid placing text or decorative elements over it. Print one proof and test with multiple camera apps under everyday lighting. If it fails, increase its size, simplify the artwork, or use a plain QR code.'],
  ] },
  { slug: 'guides', title: 'Photo QR Code Guides and Scan Tips | boring qrs', description: 'Practical guides for making image QR codes, testing artistic designs, and choosing between photo blending and AI QR artwork.', heading: 'Practical guides for artistic QR codes', sections: [
    ['Start with a link and a photo', 'You do not need an account or an AI prompt. The generator uses an image you choose and the link or text you want to encode. Read the step-by-step image QR guide to choose settings and export your first design.'],
    ['Make the design useful', 'Choose a recognizable image, explain the scan destination, and keep a visible fallback URL. The scan-testing guide covers the downloaded file, screen display, printed proofs, and common adjustments when an artistic code fails.'],
    ['Understand the limits', 'Photo blending and prompt-generated AI QR art use different workflows. Neither guarantees every design will scan. Our comparison explains what boring qrs actually does so you can choose the right approach.'],
  ] },
  { slug: 'how-to-make-a-photo-qr-code', article: true, title: 'How to Make a Photo QR Code: Step-by-Step | boring qrs', description: 'Create a QR code from a link and photo, tune strength and color, and test the PNG before using it on a card, poster, or social profile.', heading: 'How to make a photo QR code', sections: [
    ['1. Prepare your destination', 'Open your intended URL on a phone and check that it loads. Use the shortest practical URL you control; a long link makes the QR pattern more crowded. If you encode plain text, verify exactly what you want the scanner to display.'],
    ['2. Choose and upload a photo', 'Pick a portrait, landscape, or brand image with clear contrast. Crop it to emphasize one subject. In the homepage generator, enter your data and upload the image. Uploaded photos are processed locally in your browser.'],
    ['3. Tune the appearance', 'Begin with 50–70% blend strength. Compare color and grayscale. Try the detail slider and optional dithering while watching the preview. These controls change the appearance; they do not certify scannability.'],
    ['4. Export and verify', 'Scan the preview and download the PNG. Scan the exported file with two phones if available. For print, make a proof at the intended size and check it in typical lighting. Keep the border intact, and put a readable URL beside the code.'],
    ['5. Keep the destination working', 'An exported QR code stores fixed data. You can update the content on a URL you own, but cannot rewrite the URL in the existing PNG. If you change the encoded destination, generate a new QR code and replace old copies.'],
  ] },
  { slug: 'why-artistic-qr-codes-do-not-scan', article: true, title: 'Artistic QR Code Not Scanning? A Testing Guide | boring qrs', description: 'Troubleshoot image QR codes with contrast, blend strength, quiet borders, image detail, and realistic phone and print checks.', heading: 'Why an artistic QR code may not scan', sections: [
    ['Separate design problems from link problems', 'If the camera never recognizes the code, investigate the image and QR pattern. If it recognizes the code but the page fails to load, check the encoded URL and destination website. Changing the photo cannot fix a broken link.'],
    ['Reduce the blend strength', 'Strong photo blending can reduce the contrast between light and dark modules. Lower strength, switch to grayscale, and try a simpler high-contrast photo. Scan after each change so you know which adjustment helps.'],
    ['Preserve the clear border', 'Keep the light quiet zone around the code. Avoid cropping the export tightly, covering the corner markers, or placing decorative borders against the pattern. Check that the design software did not stretch the PNG or blur its edges.'],
    ['Test the real use case', 'Test the downloaded PNG, not just the large preview. Check different phones, lighting, screen brightness, and the intended viewing distance. For printed materials, scan a physical proof before ordering a batch. Use a larger or simpler code if the small version fails.'],
    ['Know what error correction can and cannot do', 'The generator uses high error correction and preserves important QR regions, but an artistic result still needs testing. Error correction does not guarantee that any amount of image blending, cropping, or low contrast will work.'],
  ] },
  { slug: 'ai-qr-code-vs-photo-qr-code', article: true, title: 'AI QR Code Art vs Photo QR Codes: What Changes? | boring qrs', description: 'Compare prompt-generated QR artwork with blending an existing photo into a QR pattern. Learn which workflow boring qrs uses.', heading: 'AI QR code art vs photo QR codes', sections: [
    ['Where the image comes from', 'Prompt-based AI QR art creates or transforms artwork with a generative model. A photo QR workflow begins with an existing image and blends it with QR modules. boring qrs follows the second workflow; it does not generate faces or landscapes from prompts.'],
    ['Control over the subject', 'With photo blending, you choose the exact portrait, landscape, or brand image to begin with. The QR pattern still changes its appearance. A generative workflow may reinterpret a subject, so the resulting artwork can differ from the source or prompt.'],
    ['Processing and privacy', 'boring qrs generates the QR and processes uploaded photos in the browser. Optional random-photo requests use an external provider. Other tools have their own processing and storage practices; check those details before sharing private images.'],
    ['Both workflows need scan checks', 'A visually impressive result is not proof that a QR scanner can read it. Test the exported image on multiple phones and at its intended size. Choose photo blending when you already have an image and want a free, no-signup workflow.'],
  ] },
  { slug: 'privacy', title: 'Privacy and Local Photo Processing | boring qrs', description: 'How boring qrs handles uploaded photos, QR content, optional external image requests, and downloaded PNG files.', heading: 'Privacy in the QR generator', sections: [
    ['Uploaded photos and QR data', 'The current generator creates QR matrices and processes uploaded images in your browser. It does not require an account or upload your selected file to an application server. Your downloaded PNG contains the QR design and its encoded link or text, so treat it as public when you share it.'],
    ['Optional external photos', 'The random-photo feature makes requests to external image services, including Unsplash when configured and Picsum as a fallback. Those services receive normal network request information. You can use your own uploaded photo without using this feature.'],
    ['Hosting and destination websites', 'The hosting provider serves this website and may process normal request logs. Scanning a link opens the encoded destination, whose privacy practices are separate. This overview describes the current implementation rather than promising that third-party sites have the same behavior.'],
    ['Your files and sharing', 'The generator has no account-based gallery or server-side image-deletion feature. Keep your original and downloaded files on your device as needed. Avoid putting passwords, private tokens, or sensitive text into a code you intend to publish.'],
  ] },
]

